version: '2.4'
services:
  backend:
    image: devtool09/backend:1.0.0
    restart : always
    ports:
    - 5000:5000
  prometheus:
    image: devtool09/promcustom
    container_name: prom
    ports:
      - 9090:9090
