version: '2.4'
services:
  backend:
    image: devtool09/backend:1.0.0
    build: ./backend
    restart : always
    ports:
    - 5000:5000
    - 9400:9400
  prometheus:
    image: devtool09/promcustom
    build: ./prometheus_custom
    container_name: prom
    ports:
      - 9090:9090